controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /user
    name_prefix: user_
    defaults:
        _format: json
user_login:
    path: /user/auth/login